package models

type BetconstructData struct {
	Command *string                 `json:"Command,omitempty"`
	Objects []Object                `json:"Objects,omitempty"`
	Error   *map[string]interface{} `json:"Error,omitempty"`
	Type    *string                 `json:"Type,omitempty"`
	Stat    Stat                    `json:"Stat,omitempty"`
	Done    bool                    `json:"Done,omitempty"`
}
type Stat struct {
	Id                   *int    `json:"Id,omitempty"`
	LangId               *string `json:"LangId,omitempty"`
	Name                 *string `json:"Name,omitempty"`
	EventId              *int    `json:"EventId,omitempty"`
	IsCancelled          *bool   `json:"IsCancelled,omitempty"`
	IsTimeout            *bool   `json:"IsTimeout,omitempty"`
	EventTimeUtc         *string `json:"EventTimeUtc,omitempty"`
	EventType            *string `json:"EventType,omitempty"`
	EventTypeId          *int    `json:"EventTypeId,omitempty"`
	Side                 *int    `json:"Side,omitempty"`
	CurrentMinute        *int    `json:"CurrentMinute,omitempty"`
	MatchLength          *int    `json:"MatchLength,omitempty"`
	Score                *string `json:"Score,omitempty"`
	CornerScore          *string `json:"CornerScore,omitempty"`
	YellowcardScore      *string `json:"YellowcardScore,omitempty"`
	RedcardScore         *string `json:"RedcardScore,omitempty"`
	ShotOnTargetScore    *string `json:"ShotOnTargetScore,omitempty"`
	ShotOffTargetScore   *string `json:"ShotOffTargetScore,omitempty"`
	DangerousAttackScore *string `json:"DangerousAttackScore,omitempty"`
	AcesScore            *string `json:"AcesScore,omitempty"`
	DoubleFaultScore     *string `json:"DoubleFaultScore,omitempty"`
	SportKind            *int    `json:"SportKind,omitempty"`
	PeriodScore          *string `json:"PeriodScore,omitempty"`
	QuarterScore         *string `json:"QuarterScore,omitempty"`
	SetScore             *string `json:"SetScore,omitempty"`
	Set1Score            *string `json:"Set1Score,omitempty"`
	Set2Score            *string `json:"Set2Score,omitempty"`
	Set3Score            *string `json:"Set3Score,omitempty"`
	Set4Score            *string `json:"Set4Score,omitempty"`
	Set5Score            *string `json:"Set5Score,omitempty"`
	Set6Score            *string `json:"Set6Score,omitempty"`
	Set7Score            *string `json:"Set7Score,omitempty"`
	Set8Score            *string `json:"Set8Score,omitempty"`
	Set9Score            *string `json:"Set9Score,omitempty"`
	Set10Score           *string `json:"Set10Score,omitempty"`
	GameScore            *string `json:"GameScore,omitempty"`
	Server               *int    `json:"Server,omitempty"`
	Info                 *string `json:"Info,omitempty"`
	RemainingTime        *string `json:"RemainingTime,omitempty"`
	Period               *int    `json:"Period,omitempty"`
	PeriodLength         *int    `json:"PeriodLength,omitempty"`
	SetCount             *int    `json:"SetCount,omitempty"`
	PenaltyScore         *string `json:"PenaltyScore,omitempty"`
	FreeKickScore        *string `json:"FreeKickScore,omitempty"`
	ExtraTimeScore       *string `json:"ExtraTimeScore,omitempty"`
	Set1YellowScore      *string `json:"Set1YellowScore,omitempty"`
	Set2YellowScore      *string `json:"Set2YellowScore,omitempty"`
	Set1CornerScore      *string `json:"Set1CornerScore,omitempty"`
	Set2CornerScore      *string `json:"Set2CornerScore,omitempty"`
	Set1RedScore         *string `json:"Set1RedScore,omitempty"`
	Set2RedScore         *string `json:"Set2RedScore,omitempty"`
	AdditionalMinutes    *int    `json:"AdditionalMinutes,omitempty"`
	TeamId               *int    `json:"TeamId,omitempty"`
}
type Object struct {
	Id                   *int             `json:"Id,omitempty"`
	LangId               *string          `json:"LangId,omitempty"`
	MatchId              *int             `json:"MatchId,omitempty"`
	NameId               *int             `json:"NameId,omitempty"`
	Handicap             *float64         `json:"Handicap,omitempty"`
	PointSequence        *int             `json:"PointSequence,omitempty"`
	CompetitionId        *int             `json:"CompetitionId,omitempty"`
	Date                 *string          `json:"Date,omitempty"`
	SportId              *int             `json:"SportId,omitempty"`
	RegionId             *int             `json:"RegionId,omitempty"`
	LiveStatus           *int             `json:"LiveStatus,omitempty"`
	MatchStatus          *int             `json:"MatchStatus,omitempty"`
	IsLiveAvailable      *bool            `json:"IsLiveAvailable,omitempty"`
	IsVisible            *bool            `json:"IsVisible,omitempty"`
	IsSuspended          *bool            `json:"IsSuspended,omitempty"`
	IsLive               *bool            `json:"IsLive,omitempty"`
	IsStarted            *bool            `json:"IsStarted,omitempty"`
	MatchMembers         []MatchMember    `json:"MatchMembers,omitempty"`
	MarketList           []Market         `json:"MarketList,omitempty"`
	Stat                 Stat             `json:"Stat,omitempty"`
	CancelReason         *string          `json:"CancelReason,omitempty"`
	IsBooked             *bool            `json:"IsBooked,omitempty"`
	Info                 *string          `json:"Info,omitempty"`
	VideoDataProviders   []*VideoProvider `json:"VideoDataProviders,omitempty"`
	IsOutright           *bool            `json:"IsOutright,omitempty"`
	Selections           []Selection      `json:"Selections,omitempty"`
	MarketTypeId         *int             `json:"MarketTypeId,omitempty"`
	Name                 *string          `json:"Name,omitempty"`
	EventId              *int             `json:"EventId,omitempty"`
	IsCancelled          *bool            `json:"IsCancelled,omitempty"`
	IsTimeout            *bool            `json:"IsTimeout,omitempty"`
	EventTimeUtc         *string          `json:"EventTimeUtc,omitempty"`
	EventType            *string          `json:"EventType,omitempty"`
	EventTypeId          *int             `json:"EventTypeId,omitempty"`
	Side                 *int             `json:"Side,omitempty"`
	CurrentMinute        *int             `json:"CurrentMinute,omitempty"`
	MatchLength          *int             `json:"MatchLength,omitempty"`
	Score                *string          `json:"Score,omitempty"`
	CornerScore          *string          `json:"CornerScore,omitempty"`
	YellowcardScore      *string          `json:"YellowcardScore,omitempty"`
	RedcardScore         *string          `json:"RedcardScore,omitempty"`
	ShotOnTargetScore    *string          `json:"ShotOnTargetScore,omitempty"`
	ShotOffTargetScore   *string          `json:"ShotOffTargetScore,omitempty"`
	DangerousAttackScore *string          `json:"DangerousAttackScore,omitempty"`
	AcesScore            *string          `json:"AcesScore,omitempty"`
	DoubleFaultScore     *string          `json:"DoubleFaultScore,omitempty"`
	SportKind            *int             `json:"SportKind,omitempty"`
	PeriodScore          *string          `json:"PeriodScore,omitempty"`
	QuarterScore         *string          `json:"QuarterScore,omitempty"`
	SetScore             *string          `json:"SetScore,omitempty"`
	Set1Score            *string          `json:"Set1Score,omitempty"`
	Set2Score            *string          `json:"Set2Score,omitempty"`
	Set3Score            *string          `json:"Set3Score,omitempty"`
	Set4Score            *string          `json:"Set4Score,omitempty"`
	Set5Score            *string          `json:"Set5Score,omitempty"`
	Set6Score            *string          `json:"Set6Score,omitempty"`
	Set7Score            *string          `json:"Set7Score,omitempty"`
	Set8Score            *string          `json:"Set8Score,omitempty"`
	Set9Score            *string          `json:"Set9Score,omitempty"`
	Set10Score           *string          `json:"Set10Score,omitempty"`
	GameScore            *string          `json:"GameScore,omitempty"`
	Server               *int             `json:"Server,omitempty"`
	RemainingTime        *string          `json:"RemainingTime,omitempty"`
	Period               *int             `json:"Period,omitempty"`
	PeriodLength         *int             `json:"PeriodLength,omitempty"`
	SetCount             *int             `json:"SetCount,omitempty"`
	PenaltyScore         *string          `json:"PenaltyScore,omitempty"`
	FreeKickScore        *string          `json:"FreeKickScore,omitempty"`
	ExtraTimeScore       *string          `json:"ExtraTimeScore,omitempty"`
	Set1YellowScore      *string          `json:"Set1YellowScore,omitempty"`
	Set2YellowScore      *string          `json:"Set2YellowScore,omitempty"`
	Set1CornerScore      *string          `json:"Set1CornerScore,omitempty"`
	Set2CornerScore      *string          `json:"Set2CornerScore,omitempty"`
	Set1RedScore         *string          `json:"Set1RedScore,omitempty"`
	Set2RedScore         *string          `json:"Set2RedScore,omitempty"`
	AdditionalMinutes    *int             `json:"AdditionalMinutes,omitempty"`
	TeamId               *int             `json:"TeamId,omitempty"`
	Kind                 *string          `json:"Kind,omitempty"`
	IsHandicap           *bool            `json:"IsHandicap,omitempty"`
	IsOverUnder          *bool            `json:"IsOverUnder,omitempty"`
	IsActive             *bool            `json:"IsActive,omitempty"`
	IsDynamic            *bool            `json:"IsDynamic,omitempty"`
	MultipleBetIndex     *int             `json:"MultipleBetIndex,omitempty"`
	Order                *int             `json:"Order,omitempty"`
	Price                *float64         `json:"Price,omitempty"`
	OriginalPrice        *float64         `json:"OriginalPrice,omitempty"`
	HomeValue            *int             `json:"HomeValue,omitempty"`
	SelectionTypeId      *int             `json:"SelectionTypeId,omitempty"`
	AwayValue            *int             `json:"AwayValue,omitempty"`
	Outcome              *int             `json:"Outcome,omitempty"`
	MarketKind           string           `json:"MarketKind,omitempty"`
}

type MatchMember struct {
	TeamId   *int    `json:"TeamId,omitempty"`
	TeamName *string `json:"TeamName,omitempty"`
	IsHome   *bool   `json:"IsHome,omitempty"`
	NameId   *uint   `json:"NameId,omitempty"`
}
type Market struct {
	Id            *uint        `json:"Id,omitempty"`
	LangId        *string      `json:"LangId,omitempty"`
	Name          *string      `json:"Name,omitempty"`
	Handicap      *float64     `json:"Handicap,omitempty"`
	Selections    []*Selection `json:"Selections,omitempty"`
	Sequence      *int         `json:"Sequence,omitempty"`
	PointSequence *int         `json:"PointSequence,omitempty"`
	IsSuspended   *bool        `json:"IsSuspended,omitempty"`
	MatchId       *int         `json:"MatchId,omitempty"`
	IsVisible     *bool        `json:"IsVisible,omitempty"`
	MarketTypeId  *int         `json:"MarketTypeId,omitempty"`
	NameId        *int         `json:"NameId,omitempty"`
}
type Selection struct {
	Id              *int     `json:"Id,omitempty"`
	LangId          *string  `json:"LangId,omitempty"`
	Name            *string  `json:"Name,omitempty"`
	Kind            *string  `json:"Kind,omitempty"`
	Order           *int     `json:"Order,omitempty"`
	Price           *float64 `json:"Price,omitempty"`
	OriginalPrice   *float64 `json:"OriginalPrice,omitempty"`
	HomeValue       *int     `json:"HomeValue,omitempty"`
	SelectionTypeId *int     `json:"SelectionTypeId,omitempty"`
	AwayValue       *int     `json:"AwayValue,omitempty"`
	IsSuspended     *bool    `json:"IsSuspended,omitempty"`
	IsVisible       *bool    `json:"IsVisible,omitempty"`
	Handicap        *float64 `json:"Handicap,omitempty"`
	NameId          *int     `json:"NameId,omitempty"`
	Outcome         *int     `json:"Outcome,omitempty"`
}
type VideoProvider struct {
	VideoProviderId *int    `json:"VideoProviderId,omitempty"`
	VideoId         *string `json:"VideoId,omitempty"`
}
